version: '3.8'

services:
  supportops:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2:-false}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - DATABASE_URL=postgresql://supportops:password@db:5432/supportops
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    networks:
      - supportops-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: supportops
      POSTGRES_USER: supportops
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - supportops-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - supportops-network

volumes:
  postgres_data:
  redis_data:

networks:
  supportops-network:
    driver: bridge