supportops:
  tribe_name: "SupportOps Tribe"
  confidence_threshold: 0.8
  max_execution_time: 1800

  # Autonomous AI Configuration
  autonomous_mode:
    enabled: true
    fallback_on_failure: true
    min_confidence_threshold: 0.7
    max_retries: 2
    timeout_seconds: 30

llm_config:
  model: "gpt-4o-mini" # Use gpt-4o-mini for better reasoning
  temperature: 0.1
  max_tokens: 4000

  # Advanced settings for autonomous agents
  autonomous_settings:
    classification_model: "gpt-4o-mini"
    analysis_model: "gpt-4o-mini"
    planning_model: "gpt-4o-mini"
    temperature: 0.1
    max_tokens: 4000
    structured_output: true

  # Fallback model for simpler tasks
  fallback_model: "gpt-4o-mini"

# Agent-specific configurations
agents:
  tribe_orchestrator:
    autonomous_classification: true
    use_historical_patterns: true
    cmdb_enrichment: true

  diagnostics_squad:
    autonomous_analysis: true
    real_time_metrics: true
    cross_correlation: true

  response_squad:
    autonomous_planning: true
    risk_assessment: true
    approval_thresholds:
      low: false
      medium: false
      high: true
      critical: true

# Monitoring and observability
monitoring:
  gpt_usage_tracking: true
  performance_metrics: true
  decision_audit_trail: true
  confidence_score_logging: true

monitoring_systems:
  prometheus:
    endpoint: "http://prometheus.internal:9090"
    auth_token: "${PROMETHEUS_TOKEN}"
  grafana:
    endpoint: "http://grafana.internal:3000"
    auth_token: "${GRAFANA_TOKEN}"

external_systems:
  servicenow:
    instance_url: "https://your-instance.service-now.com"
    username: "${SERVICENOW_USER}"
    password: "${SERVICENOW_PASS}"

  openai:
    api_key: "${OPENAI_API_KEY}"
    organization: "${OPENAI_ORG_ID}"

cloud_providers:
  aws:
    region: "us-east-1"
    access_key_id: "${AWS_ACCESS_KEY_ID}"
    secret_access_key: "${AWS_SECRET_ACCESS_KEY}"

escalation_policies:
  severity_based:
    low:
      timeout_minutes: 30
      approval_required: false
      autonomous_execution: true
    medium:
      timeout_minutes: 15
      approval_required: false
      autonomous_execution: true
    high:
      timeout_minutes: 5
      approval_required: true
      autonomous_execution: false # Require human oversight
    critical:
      timeout_minutes: 0
      approval_required: true
      autonomous_execution: false # Always require human approval

  confidence_based:
    high_confidence:
      threshold: 0.9
      auto_execute: true
    medium_confidence:
      threshold: 0.7
      require_validation: true
    low_confidence:
      threshold: 0.5
      escalate_to_human: true

# Learning and improvement
learning:
  capture_decisions: true
  feedback_collection: true
  model_fine_tuning: false # Future capability
  pattern_recognition: true
